import { StyleSheet } from "react-native";
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F5F6FA" },
  app: {
    flex: 1,
    width: "100%",
    maxWidth: 540,
    alignSelf: "center",
    backgroundColor: "#FAFBFE",
  },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderColor: "#EEF0F6",
  },
  row: { flexDirection: "row", alignItems: "center", gap: 9 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  brandIcon: {
    width: 33,
    height: 33,
    borderRadius: 10,
    backgroundColor: "#4668F5",
    alignItems: "center",
    justifyContent: "center",
  },
  brand: { fontSize: 25, fontWeight: "800", letterSpacing: -1 },
  bell: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#F5F6FA",
    alignItems: "center",
    justifyContent: "center",
  },
  notificationDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#4668F5",
    position: "absolute",
    top: 9,
    right: 9,
  },
  content: { padding: 24, gap: 17, paddingBottom: 35 },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 2.2,
    color: "#7B879F",
    fontWeight: "700",
    marginTop: 5,
  },
  heading: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "800",
    color: "#1F2942",
    letterSpacing: -0.9,
    marginTop: -5,
  },
  subtitle: { fontSize: 15, color: "#7A859C", marginTop: -8, lineHeight: 23 },
  card: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#E9EDF5",
    borderRadius: 18,
    padding: 18,
    gap: 3,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2942",
    flexShrink: 1,
  },
  body: { fontSize: 14, color: "#34405A", lineHeight: 21 },
  muted: { fontSize: 12, color: "#7A859C", lineHeight: 19 },
  small: { fontSize: 11, color: "#8A94A8", lineHeight: 17 },
  shopCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    padding: 15,
  },
  shopIcon: {
    width: 54,
    height: 64,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  dot: { width: 7, height: 7, borderRadius: 4 },
  rate: { fontSize: 11, color: "#4668F5", fontWeight: "600" },
  search: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#F0F2F7",
    borderRadius: 14,
    padding: 16,
  },
  searchInput: { flex: 1, fontSize: 14, color: "#34405A", padding: 0 },
  activeCard: { padding: 22, backgroundColor: "#4668F5", borderRadius: 21 },
  activeEyebrow: {
    color: "#DEE5FF",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  activeStatus: {
    color: "white",
    fontSize: 10,
    backgroundColor: "#FFFFFF25",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  activeTitle: {
    color: "white",
    fontSize: 22,
    fontWeight: "700",
    marginTop: 20,
  },
  activeSubtitle: { color: "#DDE4FF", marginTop: 7, fontSize: 13 },
  progress: { width: 30, height: 4, borderRadius: 2 },
  welcome: { backgroundColor: "#EEF2FF", borderRadius: 18, padding: 20 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1F2942",
    marginTop: 5,
  },
  link: { fontSize: 12, color: "#4668F5", fontWeight: "700" },
  button: {
    backgroundColor: "#4668F5",
    minHeight: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    marginTop: 5,
  },
  buttonText: { color: "white", fontSize: 14, fontWeight: "700" },
  secondaryButton: { backgroundColor: "#EEF2FF" },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  choice: {
    borderWidth: 1,
    borderColor: "#E3E7F0",
    borderRadius: 11,
    paddingVertical: 12,
    paddingHorizontal: 15,
    backgroundColor: "white",
  },
  choiceActive: { borderColor: "#4668F5", backgroundColor: "#EEF2FF" },
  choiceText: { fontSize: 13, fontWeight: "600", color: "#7A859C" },
  label: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1F2942",
    marginBottom: 12,
    marginTop: 17,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "#EEF2FF",
  },
  steps: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 10,
  },
  stepItem: { alignItems: "center", gap: 8 },
  stepCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#E8ECF5",
    alignItems: "center",
    justifyContent: "center",
  },
  selectedShop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 15,
    backgroundColor: "#EEF2FF",
    borderRadius: 13,
  },
  upload: {
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#C7D1F6",
    borderRadius: 18,
    paddingVertical: 32,
    paddingHorizontal: 15,
    alignItems: "center",
    gap: 13,
    backgroundColor: "#F3F6FF",
  },
  uploadIcon: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: "#E8EDFF",
    alignItems: "center",
    justifyContent: "center",
  },
  fileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E3E7F0",
    backgroundColor: "#FAFBFE",
    padding: 14,
    borderRadius: 12,
    fontSize: 14,
    color: "#34405A",
    marginBottom: 12,
  },
  counter: {
    width: 44,
    height: 44,
    backgroundColor: "#F0F2F7",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  divider: { height: 1, backgroundColor: "#EDF0F6", marginVertical: 16 },
  total: { fontSize: 23, fontWeight: "800", color: "#4668F5" },
  notice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 18,
    backgroundColor: "#EEF2FF",
    borderRadius: 14,
  },
  timeline: { marginTop: 20, gap: 17 },
  timelineDot: { width: 11, height: 11, borderRadius: 6 },
  pickupCode: {
    fontSize: 35,
    letterSpacing: 6,
    fontWeight: "800",
    color: "#087B57",
    marginVertical: 12,
  },
  back: { flexDirection: "row", alignItems: "center", gap: 8 },
  error: {
    padding: 15,
    borderRadius: 13,
    backgroundColor: "#FFF0F0",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  success: { padding: 16, borderRadius: 13, backgroundColor: "#EDF7F2" },
  empty: { alignItems: "center", paddingVertical: 40, gap: 14 },
  avatar: {
    width: 57,
    height: 57,
    borderRadius: 20,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  nav: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderColor: "#E9EDF5",
    backgroundColor: "white",
    paddingTop: 13,
    paddingBottom: 10,
  },
  navItem: { alignItems: "center", gap: 6, width: 65, minHeight: 51 },
  navLabel: { color: "#8D96A8", fontSize: 10, fontWeight: "600" },
  navDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: "#4668F5" },
});
